### ISSUE TITLE
Add new command by config feature request

### ISSUE THREAD

**Issue by praad** [sverrisson/mac-touchbar-commands#1]
Hello,

It would be nice if I can add new commands with config options.
For example in some cases ftp-sync command would be nice on touch bar but it is depends on a 3rd party plugin.

**Comment by sverrisson** [comment]
Hi, praad - I am sorry for not seeing this sooner.  I sent you mail and you can send a pull request.

**Comment by sverrisson** [comment]
Added in update 1.5.1. An FTP command added. To activate add in **User Settings**:  `"touchBar.ftpSync": true,`
